import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

import Toast from "@core/components/page/toast";
import ToastProvider from "@core/providers/toast-provider";
import localFont from "next/font/local";

const centraFont = localFont({
    src: "./assets/centranube-book.woff2",
    display: "swap",
    variable: "--font-centra-nube",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider localization={ptBR}>
            <html lang="en">
                <body className={`${centraFont.className}  antialiased`}>
                    <ToastProvider>
                        {children}
                        <Toast />
                    </ToastProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
